const playlist = [
    "music/Cali.mp3",
    "music/CASA.mp3",
    "music/Che dio mi benedica.mp3",
    "music/Chiasso.mp3",
    "music/Chic.mp3",
    "music/Concedimi.mp3",
    "music/Cosa mi manchi a fare.mp3",
    "music/Davide (feat. Coez).mp3",
    "music/Destri.mp3",
    "music/E yo mamma.mp3",
    "music/Estate.mp3",
    "music/Fuoco e benzina.mp3",
    "music/La Notte di San Lorenzo.mp3",
    "music/La Nuova Stella di Broadway.mp3",
    "music/Le Pietre Non Volano (feat. Marracash).mp3",
    "music/Lei È....mp3",
    "music/L'universo tranne noi.mp3",
    "music/Marylin M..mp3",
    "music/Na Na Na.mp3",
    "music/Nessuna.mp3",
    "music/Niente Canzoni D'amore.mp3",
    "music/Non Abbiamo età.mp3",
    "music/Non è mica te.mp3",
    "music/Non fare così.mp3",
    "music/Panamera.mp3",
    "music/Password.mp3",
    "music/Poetica.mp3",
    "music/Questa nostra stupida canzone d'amore.mp3",
    "music/Scale (Con Luchè).mp3",
    "music/Sei bella come Roma.mp3",
    "music/Star.mp3",
    "music/Superclassico.mp3",    
    "music/Ti Amo.mp3",
    "music/Torna Da Me.mp3",
    "music/Unica.mp3",
    "music/Uno squillo.mp3"
]